baseURL = 'https://plataformas-moviles.vercel.app'
languageCode = 'es-AR'
defaultContentLanguage = 'es'
title = 'Plataformas Móviles'
disableKinds = ['taxonomy', 'term']
theme = ["reveal-hugo"]
paginate = 999

[params]
	mainSections = ['clases']
	repository = 'https://github.com/tehuel/plataformas-moviles'

[frontmatter]
	date = [':filename', ':default']

[markup.goldmark.renderer]
	unsafe = true

[markup.goldmark.parser.attribute]
	block = true

[outputFormats.Reveal]
	mediaType = "text/html"
	isHTML = true
