name: create-post
on: workflow_dispatch
# on:
#   schedule:
#   - cron: '0 14 * * 1'
jobs:
  create-post-job:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Create Post
      run: ./create-post.sh

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
